# Use the official Nginx image as the base image
FROM nginx:latest

# Copy the HTML file to the container's filesystem
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 to allow incoming traffic
EXPOSE 80